"use strict";

/**
 * Deterministic judge-severity normalization.
 *
 * The problem: five judges rate the same forty projects. One gives 4-5 across
 * the board, one gives 2-3, one gives everything exactly 3, one alternates 1
 * and 5. Averaging those numbers is not a measurement of the projects; it is a
 * measurement of the judges. A project that happens to be reviewed by three
 * harsh judges looks worse than an identical project reviewed by three
 * generous ones.
 *
 * The model, chosen to be defensible and explainable rather than clever:
 *
 *   1. For each judge j compute mean mu_j and standard deviation sd_j over the
 *      projects they actually reviewed.
 *   2. For each individual score z_ij = (x_ij - mu_j) / sd_j.
 *   3. Shrink z toward 0 when the sample is small or the spread is near zero:
 *
 *          z_shrunk_ij = lambda_j * z_ij,   lambda_j = n_j / (n_j + K)
 *
 *      n_j = number of completed reviews by judge j. K = prior weight. A judge
 *      with 2 reviews is trusted about half as much as one with 20.
 *
 *      The division by sd_j is undefined when sd_j = 0 (the judge who rates
 *      everything 3). That case is *handled*, not divided through: when
 *      sd_j < EPS the judge carries no relative information, so z = 0 and the
 *      review is kept at its raw value with a flag. It is not deleted and it
 *      is not exploded to an arbitrary large number.
 *
 *   4. Map back to the rubric's 0-5 scale by adding the global mean and
 *      multiplying by the global standard deviation, then clamping to bounds.
 *      This keeps the result on a scale a judge can look at and argue with.
 *
 * Determinism: no randomness anywhere. Same fixtures in, same numbers out, and
 * `fingerprint()` returns a hash a judge can re-verify. `normalization-proof.md`
 * is generated by `scripts/normalization-proof.js` from this file.
 *
 * What this deliberately does NOT do: it does not change a judge's raw score,
 * and it does not reorder a project on the strength of one review. Both raw
 * and normalized are always published, and the organizer toggles between them.
 */

const EPS = 1e-9;
const PRIOR_K = 4; // shrinkage prior: a judge needs ~4 reviews for half trust

function mean(xs) {
  if (!xs.length) return 0;
  let s = 0;
  for (const x of xs) s += x;
  return s / xs.length;
}

/** Population standard deviation. The judge is the whole population here. */
function stdev(xs) {
  if (xs.length < 2) return 0;
  const m = mean(xs);
  let acc = 0;
  for (const x of xs) acc += (x - m) * (x - m);
  return Math.sqrt(acc / xs.length);
}

/**
 * @param {Array} reviews each: { judgeId, projectId, scores: {key: number} }
 * @param {Array} criteria each: { key, weight, min, max }
 * @returns {{ raw, normalized, judgeStats, global, fingerprint }}
 */
function normalize(reviews, criteria) {
  const keys = criteria.map((c) => c.key);
  const bounds = Object.fromEntries(criteria.map((c) => [c.key, { min: c.min, max: c.max }]));

  // 1. Judge statistics over the judges' own reviews.
  const byJudge = new Map();
  for (const r of reviews) {
    if (!byJudge.has(r.judgeId)) byJudge.set(r.judgeId, []);
    byJudge.get(r.judgeId).push(r);
  }

  const judgeStats = [];
  for (const [judgeId, rows] of byJudge) {
    const perKey = {};
    for (const k of keys) {
      const vals = rows.map((r) => r.scores[k]).filter((v) => Number.isFinite(v));
      perKey[k] = { n: vals.length, mean: mean(vals), sd: stdev(vals) };
    }
    const flat = rows.flatMap((r) => keys.map((k) => r.scores[k])).filter(Number.isFinite);
    const n = rows.length;
    // A judge is only *fully* degenerate when every criterion has no spread.
    // Checking just the first criterion mislabelled judges who happened to be
    // constant on functionality but variable elsewhere, which showed up in the
    // generated proof as "no spread" next to an sd of 1.1.
    const constantCriteria = keys.filter((k) => perKey[k].sd < EPS);
    judgeStats.push({
      judgeId,
      reviewCount: n,
      mean: mean(flat),
      sd: stdev(flat),
      lambda: n / (n + PRIOR_K),
      perCriterion: perKey,
      degenerate: constantCriteria.length === keys.length,
      constantCriteria,
      projects: new Set(rows.map((r) => r.projectId)).size,
    });
  }
  const statByJudge = Object.fromEntries(judgeStats.map((s) => [s.judgeId, s]));

  // 2. Global distribution, the target the normalized values are expressed in.
  const allFlat = reviews.flatMap((r) => keys.map((k) => r.scores[k])).filter(Number.isFinite);
  const global = { mean: mean(allFlat), sd: stdev(allFlat) };

  // 3. Per review: raw weighted score, then normalized weighted score.
  const wTotal = criteria.reduce((s, c) => s + (Number(c.weight) || 0), 0) || 1;
  const weightOf = (c) => (Number(c.weight) || 0) / wTotal;

  const perReview = reviews.map((r) => {
    const st = statByJudge[r.judgeId];
    const rawScores = {};
    const normScores = {};
    const flags = [];

    for (const c of criteria) {
      const x = r.scores[c.key];
      const { min, max } = bounds[c.key];
      if (!Number.isFinite(x)) {
        rawScores[c.key] = null;
        normScores[c.key] = null;
        continue;
      }
      rawScores[c.key] = x;

      const p = st.perCriterion[c.key];
      if (!p || p.n < 2) {
        /*
         * Too little of this judge's own history on this criterion to estimate
         * their severity. The earlier version kept the raw score, which is
         * backwards: a judge with a single review is the *least* trustworthy
         * one, and letting that review through at full weight defeats the
         * point of shrinkage.
         *
         * With no personal baseline, the best guess is that this judge behaves
         * like the average judge. So the score is standardized against the
         * *global* distribution instead, then shrunk by the same lambda. A
         * single review moves the result slightly; a confident judge with a
         * long record moves it fully.
         */
        const zGlobal = global.sd < EPS ? 0 : (x - global.mean) / global.sd;
        const mapped = global.mean + zGlobal * global.sd * st.lambda;
        normScores[c.key] = Math.max(min, Math.min(max, mapped));
        flags.push(`${c.key}:insufficient-judge-history`);
        continue;
      }
      if (p.sd < EPS) {
        // The judge rates this criterion identically every time. There is no
        // severity to remove, so the score is left exactly as given.
        normScores[c.key] = x;
        flags.push(`${c.key}:zero-variance-judge`);
        continue;
      }
      const z = (x - p.mean) / p.sd;
      const shrunk = z * st.lambda;
      // Back onto the rubric's own scale, centred on the global distribution.
      const mapped = global.mean + shrunk * global.sd;
      normScores[c.key] = Math.max(min, Math.min(max, mapped));
    }

    const weighted = (scores) =>
      criteria.reduce((s, c) => {
        const v = scores[c.key];
        if (!Number.isFinite(v)) return s;
        return s + weightOf(c) * v;
      }, 0);

    return {
      judgeId: r.judgeId,
      projectId: r.projectId,
      rawScores,
      normalizedScores: normScores,
      rawWeighted: weighted(rawScores),
      normalizedWeighted: weighted(normScores),
      flags: [...new Set(flags)],
    };
  });

  // 4. Aggregate to projects and rank.
  const byProject = new Map();
  for (const r of perReview) {
    if (!byProject.has(r.projectId)) byProject.set(r.projectId, []);
    byProject.get(r.projectId).push(r);
  }

  const raw = [];
  const normalized = [];
  for (const [projectId, rows] of byProject) {
    raw.push({
      projectId,
      weightedScore: mean(rows.map((r) => r.rawWeighted)),
      reviewCount: rows.length,
      judgeCount: new Set(rows.map((r) => r.judgeId)).size,
    });
    normalized.push({
      projectId,
      weightedScore: mean(rows.map((r) => r.normalizedWeighted)),
      reviewCount: rows.length,
      judgeCount: new Set(rows.map((r) => r.judgeId)).size,
      flagged: rows.some((r) => r.flags.length > 0),
    });
  }

  // Competition ranking (1,2,2,4) so a genuine tie is visible as a tie rather
  // than broken by an arbitrary tiebreak the organizer never asked for.
  const rankedRaw = rank(raw);
  const rankedNorm = rank(normalized);
  const rawRank = Object.fromEntries(rankedRaw.map((r) => [r.projectId, r]));
  const normRank = Object.fromEntries(rankedNorm.map((r) => [r.projectId, r]));

  const projects = [...new Set(perReview.map((r) => r.projectId))].map((projectId) => {
    const rr = rawRank[projectId];
    const nr = normRank[projectId];
    return {
      projectId,
      raw: rr ? { score: rr.score, rank: rr.rank, reviewCount: rr.reviewCount } : null,
      normalized: nr ? { score: nr.score, rank: nr.rank, reviewCount: nr.reviewCount } : null,
      rankMovement: rr && nr ? rr.rank - nr.rank : null,
    };
  });

  return {
    raw: rankedRaw,
    normalized: rankedNorm,
    projects,
    judgeStats,
    global,
    perReview,
    // `judgeStats` is sorted by id before fingerprinting. It is built by
    // walking a Map in first-appearance order, so hashing it raw would make
    // the fingerprint depend on the order the reviews arrived in — and a
    // "reproducible" proof whose hash moves when you re-sort the input is not
    // reproducible.
    fingerprint: fingerprint({
      rankedRaw,
      rankedNorm,
      judgeStats: [...judgeStats].sort((a, b) => a.judgeId.localeCompare(b.judgeId)),
    }),
  };
}

function rank(items) {
  const sorted = [...items].sort(
    (a, b) => b.weightedScore - a.weightedScore || a.projectId.localeCompare(b.projectId),
  );
  const out = [];
  let lastScore = null;
  let lastRank = 0;
  sorted.forEach((item, i) => {
    const score = round(item.weightedScore);
    const rank = lastScore !== null && Math.abs(score - lastScore) < EPS ? lastRank : i + 1;
    out.push({
      projectId: item.projectId,
      score: item.weightedScore,
      rank,
      reviewCount: item.reviewCount,
      judgeCount: item.judgeCount ?? item.reviewCount,
      flagged: !!item.flagged,
    });
    lastScore = score;
    lastRank = rank;
  });
  return out;
}

function round(n) {
  return Math.round(n * 1e9) / 1e9;
}

/**
 * A content hash of the whole result. Two runs over the same reviews must
 * produce the same string; a changed PRIOR_K, a changed rubric, or a changed
 * review changes it. Published in the proof so the claim is checkable.
 */
function fingerprint(payload) {
  const stable = JSON.stringify(payload, (k, v) => {
    if (v && typeof v === "object" && !Array.isArray(v)) {
      return Object.fromEntries(Object.keys(v).sort().map((kk) => [kk, v[kk]]));
    }
    return typeof v === "number" ? round(v) : v;
  });
  // eslint-disable-next-line global-require
  return require("crypto").createHash("sha256").update(stable).digest("hex").slice(0, 16);
}

module.exports = { normalize, mean, stdev, fingerprint, PRIOR_K, EPS };
