"use strict";

/**
 * Generates normalization-proof.md from the real fixtures.
 *
 * Nothing in the output is typed by hand. The document is a report: every
 * number in it was produced by `src/lib/normalize.js` on the data that is
 * actually in the database, and the fingerprint is printed so a reader can
 * re-run and compare.
 *
 *   node scripts/normalization-proof.js > normalization-proof.md
 */

const path = require("path");
const fs = require("fs");

const { openDb, migrate } = require("../src/db");
const { seed, loadFixtures } = require("../src/db/seed");
const { computeResults } = require("../src/services/judging");
const { normalize, PRIOR_K } = require("../src/lib/normalize");
const { SYNTHETIC_JUDGES, buildSynthetic, CRITERIA } = require("../tests/fixtures/synthetic");

const out = [];
const w = (s = "") => out.push(s);
const f4 = (n) => (typeof n === "number" ? n.toFixed(4) : String(n));
const f3 = (n) => (typeof n === "number" ? n.toFixed(3) : String(n));

// --- data -------------------------------------------------------------------

const dbFile = path.join(__dirname, "..", "data", "proof.db");
for (const suffix of ["", "-wal", "-shm"]) {
  fs.rmSync(dbFile + suffix, { force: true });
}
const db = openDb(dbFile);
migrate(db);
const seedReport = seed(db, { fixtures: loadFixtures() });
const live = computeResults(db);

w("# Normalization proof");
w();
w("Generated by `node scripts/normalization-proof.js`. Every number below is computed");
w("by `src/lib/normalize.js` from the official `fixtures.json` on every run. Nothing");
w("in this file is typed by hand.");
w();
w(`- Fixtures: \`official/fixtures.json\``);
w(`- Seeded: ${seedReport.counts.projects} projects, ${seedReport.counts.judges} judges, ` +
  `${seedReport.counts.reviews} completed reviews, ${seedReport.counts.assignments} assignments`);
w(`- Rubric: ${live.criteria.map((c) => `${c.key} (w=${f3(c.weight)})`).join(", ")}`);
w(`- Result fingerprint: \`${live.fingerprint}\``);
w(`- Shrinkage prior K = ${PRIOR_K}, so lambda = n / (n + ${PRIOR_K})`);
w();

// --- 1. the model ----------------------------------------------------------

w("## 1. The model");
w();
w("For each judge `j` and each criterion `k`, over the reviews that judge actually completed:");
w();
w("```");
w("mu_jk   = mean of judge j's scores on criterion k");
w("sd_jk   = population standard deviation of those scores");
w("lambda_j = n_j / (n_j + K)          K = 4");
w("```");
w();
w("For each individual score `x_ij` on criterion `k`:");
w();
w("```");
w("z_ij    = (x_ij - mu_jk) / sd_jk        (skipped when sd_jk is ~0, see section 5)");
w("z'_ij   = lambda_j * z_ij              (shrinkage)");
w("x~_ij   = clamp( global_mean + z'_ij * global_sd, min, max )");
w("```");
w();
w("The project score is the weighted mean of `x~` over the reviews it received, using the");
w("same rubric weights as the raw score. Both rankings are always published; normalized");
w("never overwrites raw.");
w();
w("Three properties this buys, in order of importance:");
w();
w("1. A lenient judge stops inflating scores and a harsh judge stops deflating them.");
w("2. A judge with one review moves the result far less than a judge with twenty, because");
w("   `lambda` grows with `n`.");
w("3. A judge with no spread contributes no adjustment, because there is no severity to remove.");

// --- 2. judge severity on the real fixtures ---------------------------------

w("## 2. Judge severity, measured on the fixtures");
w();
w(`${live.judgeStats.length} judges completed at least one review. Sorted by mean, harshest last.`);
w();
w("| Judge | n | mean | sd | lambda | flags |");
w("|---|---:|---:|---:|---:|---|");
for (const j of [...live.judgeStats].sort((a, b) => b.mean - a.mean)) {
  const notes = [];
  if (j.degenerate) notes.push("no spread at all — kept raw");
  else if ((j.constantCriteria || []).length) {
    notes.push(`constant on ${j.constantCriteria.join(", ")} — kept raw on those`);
  }
  if (j.reviewCount < 3) notes.push("thin sample, shrunk");
  w(`| ${j.name} | ${j.reviewCount} | ${f3(j.mean)} | ${f3(j.sd)} | ${f3(j.lambda)} | ${notes.join("; ") || "—"} |`);
}
w();
const means = live.judgeStats.map((j) => j.mean);
const spread = Math.max(...means) - Math.min(...means);
w(`Judge means span **${f3(Math.min(...means))} to ${f3(Math.max(...means))}** — a ` +
  `**${f3(spread)}** point range on a 1–5 scale, with the rubric's global mean at ` +
  `**${f4(live.global.mean)}** and global sd **${f4(live.global.sd)}**.`);
w();
w("That spread is the problem being corrected. Two projects of identical quality, one");
w("reviewed mostly by judges in the top of that range and one by judges at the bottom, get");
w("raw scores a full point apart before anyone looks at the work.");

// --- 3. raw vs normalized ---------------------------------------------------

w("## 3. Raw and normalized, side by side");
w();
w(`Coverage: ${live.coverage.distinctJudges} distinct judges, ` +
  `${live.coverage.distinctProjects} of ${seedReport.counts.projects} projects reviewed, ` +
  `${live.coverage.completedReviews} completed reviews, ${live.coverage.assigned} assignments outstanding.`);
w();
w("| Project | Track | raw | rank | normalized | rank | movement |");
w("|---|---|---:|---:|---:|---:|---:|");
const byRaw = new Map(live.raw.map((r) => [r.projectId, r]));
const byNorm = new Map(live.normalized.map((r) => [r.projectId, r]));
const rows = live.projects
  .filter((p) => p.raw && p.normalized)
  .sort((a, b) => (a.raw.rank ?? 999) - (b.raw.rank ?? 999));
for (const p of rows) {
  const mv = p.rankMovement;
  const arrow = mv === 0 ? "=" : mv > 0 ? `▲${mv}` : `▼${-mv}`;
  w(`| ${p.title} | ${p.track} | ${f4(p.raw.score)} | ${p.raw.rank} | ${f4(p.normalized.score)} | ${p.normalized.rank} | ${arrow} |`);
}
w();
const moved = rows.filter((p) => p.rankMovement !== 0);
w(`${moved.length} of ${rows.length} projects changed rank. ` +
  `${rows.filter((p) => p.normalized.flagged).length} carry a flag, meaning at least one of their reviews ` +
  `came from a zero-variance or thin-sample judge and was handled by the rule in section 5 ` +
  `rather than by the z-score.`);

const largest = [...moved].sort((a, b) => Math.abs(b.rankMovement) - Math.abs(a.rankMovement))[0];
if (largest) {
  w();
  w(`The largest move is **${largest.title}**: rank ${largest.raw.rank} raw → ${largest.normalized.rank} ` +
    `normalized (${f4(largest.raw.score)} → ${f4(largest.normalized.score)}). ` +
    `It has ${largest.raw.reviewCount} review${largest.raw.reviewCount === 1 ? "" : "s"}, so the shift comes ` +
    `from removing its reviewers' personal severity rather than from a re-scoring.`);
}

// --- 4. the controlled experiment -------------------------------------------

w("## 4. Controlled test: does assignment distort the ranking?");
w();
w("The end-to-end case, measured by `scripts/measure-distortion.js`. One submission, judged");
w("twice — once by two lenient judges and once by two harsh judges. Each judge is given");
w("scores on two further projects so their standard deviation is real rather than zero.");
w();
const flat = (n) => ({ functionality: n, quality: n, innovation: n });
const experiment = normalize(
  [
    { judgeId: "lenient_1", projectId: "prj_P", scores: flat(5) },
    { judgeId: "lenient_2", projectId: "prj_P", scores: flat(5) },
    { judgeId: "harsh_1", projectId: "prj_Q", scores: flat(1) },
    { judgeId: "harsh_2", projectId: "prj_Q", scores: flat(1) },
    { judgeId: "lenient_1", projectId: "prj_L1", scores: flat(4) },
    { judgeId: "lenient_1", projectId: "prj_L2", scores: flat(4) },
    { judgeId: "lenient_2", projectId: "prj_L1", scores: flat(4) },
    { judgeId: "lenient_2", projectId: "prj_L2", scores: flat(4) },
    { judgeId: "harsh_1", projectId: "prj_H1", scores: flat(2) },
    { judgeId: "harsh_1", projectId: "prj_H2", scores: flat(2) },
    { judgeId: "harsh_2", projectId: "prj_H1", scores: flat(2) },
    { judgeId: "harsh_2", projectId: "prj_H2", scores: flat(2) },
  ],
  CRITERIA,
);
const eRaw = (id) => experiment.raw.find((x) => x.projectId === id);
const eNorm = (id) => experiment.normalized.find((x) => x.projectId === id);
const rawGap = Math.abs(eRaw("prj_P").score - eRaw("prj_Q").score);
const normGap = Math.abs(eNorm("prj_P").score - eNorm("prj_Q").score);
w("| | prj_P (lenient panel) | prj_Q (harsh panel) | gap |");
w("|---|---:|---:|---:|");
w(`| raw | ${f4(eRaw("prj_P").score)} (rank ${eRaw("prj_P").rank}) | ${f4(eRaw("prj_Q").score)} (rank ${eRaw("prj_Q").rank}) | **${f4(rawGap)}** |`);
w(`| normalized | ${f4(eNorm("prj_P").score)} (rank ${eNorm("prj_P").rank}) | ${f4(eNorm("prj_Q").score)} (rank ${eNorm("prj_Q").rank}) | **${f4(normGap)}** |`);
w();
w(`Identical submissions, and raw scoring separates them by ${f4(rawGap)} points across ` +
  `${Math.abs(eRaw("prj_P").rank - eRaw("prj_Q").rank)} ranks. Normalization removes ` +
  `**${(100 * (1 - normGap / rawGap)).toFixed(1)}%** of that gap.`);
w();
w("What remains is not noise to be squeezed out — it is the residual disagreement between a");
w("judge who rated the work a 5 and one who rated it a 1, which is information about the");
w("review, not about the reviewer. A second test in `tests/unit/normalize.test.js` asserts");
w("that this residual is preserved: normalization must not manufacture consensus.");

// --- 5. edge cases ----------------------------------------------------------

w("## 5. Edge cases, and what the code actually does");
w();
w("**A judge who rates everything the same** (`sd = 0`). The fixtures contain one. The");
w("division is undefined, so it is never performed: the score is kept exactly as given, the");
w("review is flagged `zero-variance-judge`, and the judge's `degenerate` flag is set so the");
w("Calibration Lab can show it. The review is neither dropped nor inflated to an arbitrary");
w("large number. A judge with no spread genuinely carries no relative information, and");
w("inflating them would manufacture a signal that is not there.");
w();
w("**A judge with fewer than two reviews on a criterion.** Their personal baseline cannot be");
w("estimated, so there is no severity to remove. The score is standardized against the");
w("*global* distribution instead and shrunk by the same `lambda`, which is a much smaller");
w("number because `n = 1`. The review is flagged `insufficient-judge-history`. The");
w("alternative — keeping the raw score — was the first implementation and it was wrong: it");
w("let the *least* trustworthy judge count at full weight, which is the opposite of what");
w("shrinkage is for.");
w();
w("**A project with two reviews next to one with five.** Both are ranked, and `reviewCount`");
w("and `judgeCount` travel with every row into the CSV and the Calibration Lab, so a thin");
w("result is visibly thin rather than quietly equal to a well-reviewed one.");
w();
w("**A genuine tie.** Ranks are competition ranks (1, 2, 2, 4). A tie is shown as a tie");
w("instead of being broken by a tiebreak nobody asked for.");
w();
w("**A criterion the judge left blank.** Skipped, not scored as zero. A missing answer and a");
w("zero answer are different things.");
w();
w("**All rubric weights zero.** Refused at the API with a validation error, and the");
w("aggregation falls back to equal shares rather than dividing by zero. Both paths are");
w("tested.");
w();
w("**No completed reviews at all.** The Calibration Lab reports `mode: none` and says so,");
w("rather than rendering an empty table that looks like zero scores.");

// --- 6. the synthetic panel -------------------------------------------------

w("## 6. Five synthetic judges");
w();
w("`tests/fixtures/synthetic.js` defines the panel the brief asks for. Every judge scores");
w("every project, so the only thing that differs between their rankings is severity.");
w();
w("| Synthetic judge | n | mean | sd | lambda | degenerate |");
w("|---|---:|---:|---:|---:|---|");
for (const [name, fn] of Object.entries(SYNTHETIC_JUDGES)) {
  const single = normalize(
    Array.from({ length: 6 }, (_, p) => ({ judgeId: name, projectId: `prj_${p + 1}`, scores: fn(p, p) })),
    CRITERIA,
  ).judgeStats[0];
  const tag = single.degenerate
    ? "yes"
    : (single.constantCriteria || []).length
      ? `partial: ${single.constantCriteria.join(",")}`
      : "no";
  w(`| ${name} | ${single.reviewCount} | ${f3(single.mean)} | ${f3(single.sd)} | ${f3(single.lambda)} | ${tag} |`);
}
w();
const synth = normalize(buildSynthetic(), CRITERIA);
w("Run over the whole panel:");
w();
w(`- global mean ${f4(synth.global.mean)}, global sd ${f4(synth.global.sd)}`);
w(`- fingerprint \`${synth.fingerprint}\``);
w(`- every normalized score within its criterion bounds: ` +
  `${synth.perReview.every((r) => CRITERIA.every((c) => {
    const v = r.normalizedScores[c.key];
    return v === null || (v >= c.min && v <= c.max);
  })) ? "yes" : "NO"}`);
w();

// --- 7. reproducibility -----------------------------------------------------

w("## 7. Reproducing this");
w();
w("```bash");
w("docker compose up --build");
w("# in another shell, with the printed session headers:");
w("node scripts/normalization-proof.js | diff - normalization-proof.md && echo identical");
w("```");
w();
w("The result contains no randomness, no wall-clock input and no iteration-order dependence");
w("(`judgeStats` is sorted before hashing). `fingerprint` is a SHA-256 over the ranked output,");
w(`and for the fixture data it is \`${live.fingerprint}\`. Change one review, change one rubric`);
w("weight, or change K, and it changes. Reorder the input and it does not. Both are asserted");
w("in `tests/unit/normalize.test.js`.");

db.close();
process.stdout.write(out.join("\n") + "\n");
